export default [
  {
    files: ["merlinclash/res/mc-menu.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        location: "readonly",
        navigator: "readonly",
        setTimeout: "readonly",
        getComputedStyle: "readonly",
        $: "readonly",
        jQuery: "readonly",
        dbus: "readonly",
        http_response: "readonly",
        // Router firmware Web UI globals
        db_merlinclash: "writable",
        clientList: "writable",
        control_dropdown_client_block: "readonly",
        disableCheckChangedStatus: "readonly",
        genClientList: "readonly",
        htmlbodyforIE: "readonly",
        loadingSeconds: "writable",
        optsCount: "writable",
        overlib: "readonly",
        progress: "readonly",
        refreshpage: "readonly",
        removeElement: "readonly",
        statusmenu: "readonly",
        tablink: "writable",
        tabtitle: "writable",
        winH: "writable",
        winHeight: "writable",
        winPadding: "writable",
        winW: "writable",
        winW_H: "writable",
        winWidth: "writable",
        action: "writable",
        bgcolor: "writable",
        width: "writable",
        x: "writable",
        y: "writable",
        CAPTION: "readonly",
        CLOSETITLE: "readonly",
        LEFT: "readonly",
        OFFSETX: "readonly",
        OFFSETY: "readonly",
        STICKY: "readonly",
        WIDTH: "readonly",
        _caption: "readonly",
        // base2 / Packer runtime globals (evaluated via eval string exports)
        Base: "writable",
        Collection: "writable",
        K: "writable",
        Packer: "writable",
        RegGrp: "writable",
        StopIteration: "writable",
        Undefined: "writable",
        extend: "writable",
        forEach: "writable",
        format: "writable",
        global: "writable",
        id: "writable",
        match: "writable",
        rescape: "writable",
        typeOf: "writable"
      }
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
      "no-unreachable": "error",
      "no-dupe-keys": "error"
    }
  }
];
