#!/bin/sh
. /jffs/softcenter/scripts/base.sh
. /jffs/softcenter/scripts/clash_safe.sh || exit 1
SC=/jffs/softcenter
MC_DIR=$SC/merlinclash
umask 077
# Uninstall needs cleanup even when interrupted profile recovery is impossible.
mc_lock --cleanup-only || exit 1
WORK=$(mc_mktemp -d /tmp/mc-uninstall.XXXXXX) || { mc_unlock; exit 1; }
finish() { status=$?; trap - EXIT HUP INT TERM; rm -rf "$WORK"; mc_unlock; exit "$status"; }
trap finish EXIT
trap 'exit 1' HUP INT TERM

# Disable and stop through the one lifecycle owner before removing its files.
# Flags and a missing core do not prove owned DNS/firewall state was removed.
sh "$SC/scripts/clash_config.sh" stop stop >/dev/null 2>&1 || exit 1
[ -z "$(mc_core_pids)" ] && ! mc_owned_state_present || exit 1
dbus set merlinclash_enable=0 || exit 1
dbus set merlinclash_recovery_wanted=0 || exit 1

# Generic historical job names belong to the plugin only when their command does.
cru l > "$WORK/cron" || exit 1
for job in merlinclash_autoupdate clash_watchdog clash_restart regular_subscribe d2s_watchdog clash_prenetflix autosermark autologdel autoupdate merlinclash_subscription merlinclash_logdelete merlinclash_setmark; do
    if awk -v job="$job" '$0 ~ ("#" job "#") && ($0 ~ /\/jffs\/softcenter\/scripts\/(clash_[A-Za-z0-9_]+|merlinclash_autoupdate)\.sh/ || $0 ~ /\/jffs\/softcenter\/merlinclash\/clashconfig\.sh/) {found=1} END {exit !found}' "$WORK/cron"; then
        cru d "$job" || exit 1
    fi
done

strip_owned_blocks() {
    file=$1
    [ -f "$file" ] || return 0
    temp=$(mc_mktemp "$file.mc-uninstall.XXXXXX") || return 1
    cp -p "$file" "$temp" || { rm -f "$temp"; return 1; }
    # Marker blocks are generated by the repaired router hook installer. Preserve
    # every other line, including NAS forwarding, swap and unrelated VPN hooks.
    awk '
        $0 == "# BEGIN Magic Catling 2" { if (inside) bad=1; inside=1; next }
        $0 == "# END Magic Catling 2" { if (!inside) bad=1; inside=0; next }
        !inside { print }
        END { if (inside || bad) exit 1 }
    ' "$file" > "$temp" || { rm -f "$temp"; return 1; }
    sh -n "$temp" || { rm -f "$temp"; return 1; }
    mv -f "$temp" "$file"
}
for file in /jffs/scripts/services-start /jffs/scripts/firewall-start /jffs/scripts/nat-start /jffs/scripts/services-stop; do
    strip_owned_blocks "$file" || exit 1
done
# Older standalone custom registrations are removed only by exact command path.
for file in /jffs/scripts/services-start /jffs/scripts/firewall-start /jffs/scripts/nat-start; do
    [ -f "$file" ] || continue
    temp=$(mc_mktemp "$file.mc-uninstall.XXXXXX") || exit 1
    cp -p "$file" "$temp" || { rm -f "$temp"; exit 1; }
    awk '
        /^cru a (merlinclash_autoupdate|clash_watchdog) / && /\/jffs\/softcenter\/scripts\/(merlinclash_autoupdate|clash_watchdog)\.sh/ {next}
        /^\/jffs\/scripts\/(chatgpt-http3|chatgpt-quic-fallback|merlinclash-listener-guard)\.sh([[:space:]]|$)/ {next}
        {print}
    ' "$file" > "$temp" || exit 1
    sh -n "$temp" && mv -f "$temp" "$file" || { rm -f "$temp"; exit 1; }
done

# dnsmasq hooks may also contain user/VPN configuration. Only remove a proven
# plugin-owned link or a byte-identical copy of its supplied hook.
for file in /jffs/scripts/dnsmasq.postconf /jffs/scripts/dnsmasq-sdn.postconf; do
    if [ -L "$file" ]; then
        case "$(readlink "$file")" in "$MC_DIR"/*) rm -f "$file" || exit 1;; esac
    elif [ -f "$file" ]; then
        if [ -f "$MC_DIR/conf/dnsmasq.postconf" ] && cmp -s "$file" "$MC_DIR/conf/dnsmasq.postconf"; then
            rm -f "$file" || exit 1
        else
            strip_owned_blocks "$file" || exit 1
        fi
    fi
done
if [ -f /jffs/scripts/chatgpt-http3.sh ]; then sh /jffs/scripts/chatgpt-http3.sh --remove || exit 1; fi

# Exact init aliases avoid deleting another plugin's similarly named startup.
for file in "$SC/init.d/S150merlinclash.sh" "$SC/init.d/N150merlinclash.sh"; do
    if [ -L "$file" ]; then
        case "$(readlink "$file")" in "$SC/scripts/clash_config.sh"|"$MC_DIR/clashconfig.sh") rm -f "$file" || exit 1;; esac
    fi
done
for file in "$SC/bin/clash" "$SC/res/icon-merlinclash.png" "$SC/res/merlinclash.css" "$SC/res/mc-tablednd.js" "$SC/res/mc-menu.js" "$SC/webs/Module_merlinclash.asp" /jffs/scripts/chatgpt-http3.sh /jffs/scripts/chatgpt-quic-fallback.sh /jffs/scripts/merlinclash-listener-guard.sh "$SC/scripts/merlinclash_autoupdate.sh" "$SC/scripts/fix_merlinclash_ports.sh"; do
    rm -f "$file" || exit 1
done
for file in "$SC"/scripts/clash*.sh "$SC"/res/clash* /tmp/etc/dnsmasq.user/clash* /tmp/upload/clash_* /tmp/upload/merlinclash*; do
    [ -e "$file" ] || [ -L "$file" ] || continue
    rm -rf "$file" || exit 1
done
if [ -L /tmp/upload/yamls.txt ] && [ "$(readlink /tmp/upload/yamls.txt)" = "$MC_DIR/yaml_bak/yamls.txt" ]; then rm -f /tmp/upload/yamls.txt || exit 1; fi
rm -rf "$MC_DIR" || exit 1
# yq is shared with other softcenter plugins and is intentionally retained.
dbus list merlinclash_ > "$WORK/dbus" || exit 1
while IFS= read -r record; do dbus remove "${record%%=*}" || exit 1; done < "$WORK/dbus"
dbus list softcenter_module_merlinclash_ > "$WORK/dbus" || exit 1
while IFS= read -r record; do dbus remove "${record%%=*}" || exit 1; done < "$WORK/dbus"
rm -f "$SC/scripts/merlinclash_install.sh" "$SC/scripts/uninstall_merlinclash.sh" || exit 1
